export const GET_BOARDS_SUCCESS = 'GET_BOARDS_SUCCESS';
export const GET_BOARDS_FAILURE = 'GET_BOARDS_FAILURE';
export const ADD_BOARD_SUCCESS = 'ADD_BOARD_SUCCESS';
export const ADD_BOARD_FAILURE = 'ADD_BOARD_FAILURE';
export const GET_BOARD_BY_ID_SUCCESS = 'GET_BOARD_BY_ID_SUCCESS';
export const GET_BOARD_BY_ID_FAILURE = 'GET_BOARD_BY_ID_FAILURE';
export const GET_BOARDS_BY_USER_SUCCESS = 'GET_BOARDS_BY_USER_SUCCESS';
export const GET_BOARDS_BY_USER_FAILURE = 'GET_BOARDS_BY_USER_FAILURE';
