export const GET_BOARDS_SUCCESS = 'GET_BOARDS_SUCCESS';
export const GET_BOARDS_FAILURE = 'GET_BOARDS_FAILURE';
export const ADD_BOARDS_SUCCESS = 'ADD_BOARDS_SUCCESS';
export const ADD_BOARDS_FAILURE = 'ADD_BOARDS_FAILURE';
