export const GET_LISTS_SUCCESS = 'GET_LISTS_SUCCESS';
export const GET_LISTS_FAILURE = 'GET_LISTS_FAILURE';
export const ADD_LISTS_SUCCESS = 'ADD_LISTS_SUCCESS';
export const ADD_LISTS_FAILURE = 'ADD_LISTS_FAILURE';
