export const GET_LISTS_SUCCESS = 'GET_LISTS_SUCCESS';
export const GET_LISTS_FAILURE = 'GET_LISTS_FAILURE';
export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS';
export const ADD_LIST_FAILURE = 'ADD_LIST_FAILURE';
export const GET_LISTS_BY_BOARD_SUCCESS = 'GET_LISTS_BY_BOARD_SUCCESS';
export const GET_LISTS_BY_BOARD_FAILURE = 'GET_LISTS_BY_BOARD_FAILURE';
