export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';
export const GET_TASKS_BY_LIST_SUCCESS = 'GET_TASKS_BY_LIST_SUCCESS';
export const GET_TASKS_BY_LIST_FAILURE = 'GET_TASKS_BY_LIST_FAILURE';
export const CHANGE_TASK_SUCCESS = 'CHANGE_TASK_SUCCESS';
export const CHANGE_TASK_FAILURE = 'CHANGE_TASK_FAILURE';
